//DATA
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_FAILURE = "GET_DATA_FAILURE"
export const GET_FILM_DATA = "GET_FILM_DATA"
export const GET_FILTERED_FILMS = "GET_FILTERED_FILMS"
export const GET_SORTED_FILMS = "GET_SORTED_FILMS"
